# To allow your IDE to autocomplete and validate your YAML pipelines, name them as <name of your choice>.haystack-pipeline.yml

version: ignore

components:    # define all the building-blocks for Pipeline
  - name: DocumentStore
    type: ElasticsearchDocumentStore
    params:
      analyzer: portuguese
      embedding_dim: 768
      similarity: cosine
      host: localhost
  - name: ESRetriever
    type: BM25Retriever
    params:
      document_store: DocumentStore
      top_k: 30
  - name: DPRRetriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore
      embedding_model: rufimelo/Legal-SBERTimbau-sts-base
      model_format: sentence_transformers
      top_k: 30
  - name: JoinResults
    type: JoinDocuments
    params: {}
  - name: Ranker
    type: SentenceTransformersRanker
    params:
      model_name_or_path: cross-encoder/ms-marco-MiniLM-L-12-v2
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      clean_empty_lines: True
      clean_whitespace: True
      clean_header_footer: False
      split_by: word
      split_length: 100
      split_respect_sentence_boundary: True
      language: pt
  - name: FileTypeClassifier
    type: FileTypeClassifier

pipelines:
  - name: query
    nodes:
      - name: ESRetriever
        inputs: [Query]
      - name: DPRRetriever
        inputs: [Query]
      - name: JoinResults
        inputs: [ESRetriever, DPRRetriever]
      #- name: Ranker
      #  inputs: [JoinResults]
  - name: indexing
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: DPRRetriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [DPRRetriever]
